sudo: required
language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  - gem 'aws-sdk', '~> 3'
  - docker build -t douglasrosa16/docker-back-postgres -f Dockerfile.dev .

services:
  - docker

script:
  - docker run -e CI=true douglasrosa16/docker-back-postgres npm run test -- --coverage #Fazer isso para executar os testes e encerrar

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "backendprestserv"
  env: "Backendprestserv-env"
  bucket_name: "backendprestserv"
  skip_cleanup: true
  on:
    branch: master
