sudo: required
language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  - docker build -t douglasrosa16/docker-back-postgres -f Dockerfile .

script:
  - docker run douglasrosa16/docker-back-postgres npm run test -- --coverage #Fazer isso para executar os testes e encerrar

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "prest_serv_back"
  env: "Prestservback-env"
  bucket_name: "prestacaoservicoback"
  skip_cleanup: true
  on:
    branch: master
